Feature enhancement (4/5)

diff --git a/apache-maven-3.9.9/bin/mvnyjp b/apache-maven-3.9.9/bin/mvnyjp
--- a/apache-maven-3.9.9/bin/mvnyjp
+++ b/apache-maven-3.9.9/bin/mvnyjp
@@ -22,3 +22,11 @@
 #
 # Environment Variable Prerequisites
 #
+#   JAVA_HOME       Must point at your Java Development Kit installation.
+#   MAVEN_ARGS      (Optional) Arguments passed to Maven before CLI arguments.
+#   MAVEN_OPTS      (Optional) Java runtime options used when Maven is executed.
+#   MAVEN_SKIP_RC   (Optional) Flag to disable loading of mavenrc files.
+# -----------------------------------------------------------------------------
+
+if [ ! -f "$YJPLIB" ]; then
+  echo "Error: Unable to autodetect the YJP library location. Please set YJPLIB variable" >&2
